/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SkControlPanel99RouteImport } from './routes/sk-control-panel-99'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityLogsRouteImport } from './routes/security-logs'
import { Route as PublishersRouteImport } from './routes/publishers'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SkControlPanel99Route = SkControlPanel99RouteImport.update({
  id: '/sk-control-panel-99',
  path: '/sk-control-panel-99',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityLogsRoute = SecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishersRoute = PublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/publishers': typeof PublishersRoute
  '/security-logs': typeof SecurityLogsRoute
  '/settings': typeof SettingsRoute
  '/sk-control-panel-99': typeof SkControlPanel99Route
  '/submissions': typeof SubmissionsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/publishers': typeof PublishersRoute
  '/security-logs': typeof SecurityLogsRoute
  '/settings': typeof SettingsRoute
  '/sk-control-panel-99': typeof SkControlPanel99Route
  '/submissions': typeof SubmissionsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/publishers': typeof PublishersRoute
  '/security-logs': typeof SecurityLogsRoute
  '/settings': typeof SettingsRoute
  '/sk-control-panel-99': typeof SkControlPanel99Route
  '/submissions': typeof SubmissionsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeals'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/publishers'
    | '/security-logs'
    | '/settings'
    | '/sk-control-panel-99'
    | '/submissions'
    | '/tasks'
    | '/users'
    | '/app/dashboard'
    | '/app/profile'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeals'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/publishers'
    | '/security-logs'
    | '/settings'
    | '/sk-control-panel-99'
    | '/submissions'
    | '/tasks'
    | '/users'
    | '/app/dashboard'
    | '/app/profile'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/appeals'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/publishers'
    | '/security-logs'
    | '/settings'
    | '/sk-control-panel-99'
    | '/submissions'
    | '/tasks'
    | '/users'
    | '/app/dashboard'
    | '/app/profile'
    | '/auth/login'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealsRoute: typeof AppealsRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PublishersRoute: typeof PublishersRoute
  SecurityLogsRoute: typeof SecurityLogsRoute
  SettingsRoute: typeof SettingsRoute
  SkControlPanel99Route: typeof SkControlPanel99Route
  SubmissionsRoute: typeof SubmissionsRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sk-control-panel-99': {
      id: '/sk-control-panel-99'
      path: '/sk-control-panel-99'
      fullPath: '/sk-control-panel-99'
      preLoaderRoute: typeof SkControlPanel99RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-logs': {
      id: '/security-logs'
      path: '/security-logs'
      fullPath: '/security-logs'
      preLoaderRoute: typeof SecurityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishers': {
      id: '/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof PublishersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealsRoute: AppealsRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PublishersRoute: PublishersRoute,
  SecurityLogsRoute: SecurityLogsRoute,
  SettingsRoute: SettingsRoute,
  SkControlPanel99Route: SkControlPanel99Route,
  SubmissionsRoute: SubmissionsRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
