/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppWithdrawRouteImport } from './routes/app/withdraw'
import { Route as AppWalletRouteImport } from './routes/app/wallet'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppSubmissionsRouteImport } from './routes/app/submissions'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppReferralsRouteImport } from './routes/app/referrals'
import { Route as AppPublishRouteImport } from './routes/app/publish'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppDepositRouteImport } from './routes/app/deposit'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAppealsRouteImport } from './routes/app/appeals'
import { Route as Skabdullah_999_sgAdminUsersRouteImport } from './routes/skabdullah_999_sg.admin.users'
import { Route as Skabdullah_999_sgAdminTutorialsRouteImport } from './routes/skabdullah_999_sg.admin.tutorials'
import { Route as Skabdullah_999_sgAdminTasksRouteImport } from './routes/skabdullah_999_sg.admin.tasks'
import { Route as Skabdullah_999_sgAdminSettingsRouteImport } from './routes/skabdullah_999_sg.admin.settings'
import { Route as Skabdullah_999_sgAdminSecurityLogsRouteImport } from './routes/skabdullah_999_sg.admin.security-logs'
import { Route as Skabdullah_999_sgAdminPublishersRouteImport } from './routes/skabdullah_999_sg.admin.publishers'
import { Route as Skabdullah_999_sgAdminPaymentsRouteImport } from './routes/skabdullah_999_sg.admin.payments'
import { Route as Skabdullah_999_sgAdminNotificationsRouteImport } from './routes/skabdullah_999_sg.admin.notifications'
import { Route as Skabdullah_999_sgAdminLoginRouteImport } from './routes/skabdullah_999_sg.admin.login'
import { Route as Skabdullah_999_sgAdminDashboardRouteImport } from './routes/skabdullah_999_sg.admin.dashboard'
import { Route as Skabdullah_999_sgAdminAppealsRouteImport } from './routes/skabdullah_999_sg.admin.appeals'
import { Route as AppTasksTaskIdRouteImport } from './routes/app/tasks.$taskId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAppealsRoute = AppAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AppRoute,
} as any)
const Skabdullah_999_sgAdminUsersRoute =
  Skabdullah_999_sgAdminUsersRouteImport.update({
    id: '/skabdullah_999_sg/admin/users',
    path: '/skabdullah_999_sg/admin/users',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminTutorialsRoute =
  Skabdullah_999_sgAdminTutorialsRouteImport.update({
    id: '/skabdullah_999_sg/admin/tutorials',
    path: '/skabdullah_999_sg/admin/tutorials',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminTasksRoute =
  Skabdullah_999_sgAdminTasksRouteImport.update({
    id: '/skabdullah_999_sg/admin/tasks',
    path: '/skabdullah_999_sg/admin/tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminSettingsRoute =
  Skabdullah_999_sgAdminSettingsRouteImport.update({
    id: '/skabdullah_999_sg/admin/settings',
    path: '/skabdullah_999_sg/admin/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminSecurityLogsRoute =
  Skabdullah_999_sgAdminSecurityLogsRouteImport.update({
    id: '/skabdullah_999_sg/admin/security-logs',
    path: '/skabdullah_999_sg/admin/security-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminPublishersRoute =
  Skabdullah_999_sgAdminPublishersRouteImport.update({
    id: '/skabdullah_999_sg/admin/publishers',
    path: '/skabdullah_999_sg/admin/publishers',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminPaymentsRoute =
  Skabdullah_999_sgAdminPaymentsRouteImport.update({
    id: '/skabdullah_999_sg/admin/payments',
    path: '/skabdullah_999_sg/admin/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminNotificationsRoute =
  Skabdullah_999_sgAdminNotificationsRouteImport.update({
    id: '/skabdullah_999_sg/admin/notifications',
    path: '/skabdullah_999_sg/admin/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminLoginRoute =
  Skabdullah_999_sgAdminLoginRouteImport.update({
    id: '/skabdullah_999_sg/admin/login',
    path: '/skabdullah_999_sg/admin/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminDashboardRoute =
  Skabdullah_999_sgAdminDashboardRouteImport.update({
    id: '/skabdullah_999_sg/admin/dashboard',
    path: '/skabdullah_999_sg/admin/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const Skabdullah_999_sgAdminAppealsRoute =
  Skabdullah_999_sgAdminAppealsRouteImport.update({
    id: '/skabdullah_999_sg/admin/appeals',
    path: '/skabdullah_999_sg/admin/appeals',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submissions': typeof SubmissionsRoute
  '/app/appeals': typeof AppAppealsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/publish': typeof AppPublishRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/skabdullah_999_sg/admin/appeals': typeof Skabdullah_999_sgAdminAppealsRoute
  '/skabdullah_999_sg/admin/dashboard': typeof Skabdullah_999_sgAdminDashboardRoute
  '/skabdullah_999_sg/admin/login': typeof Skabdullah_999_sgAdminLoginRoute
  '/skabdullah_999_sg/admin/notifications': typeof Skabdullah_999_sgAdminNotificationsRoute
  '/skabdullah_999_sg/admin/payments': typeof Skabdullah_999_sgAdminPaymentsRoute
  '/skabdullah_999_sg/admin/publishers': typeof Skabdullah_999_sgAdminPublishersRoute
  '/skabdullah_999_sg/admin/security-logs': typeof Skabdullah_999_sgAdminSecurityLogsRoute
  '/skabdullah_999_sg/admin/settings': typeof Skabdullah_999_sgAdminSettingsRoute
  '/skabdullah_999_sg/admin/tasks': typeof Skabdullah_999_sgAdminTasksRoute
  '/skabdullah_999_sg/admin/tutorials': typeof Skabdullah_999_sgAdminTutorialsRoute
  '/skabdullah_999_sg/admin/users': typeof Skabdullah_999_sgAdminUsersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submissions': typeof SubmissionsRoute
  '/app/appeals': typeof AppAppealsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/publish': typeof AppPublishRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/skabdullah_999_sg/admin/appeals': typeof Skabdullah_999_sgAdminAppealsRoute
  '/skabdullah_999_sg/admin/dashboard': typeof Skabdullah_999_sgAdminDashboardRoute
  '/skabdullah_999_sg/admin/login': typeof Skabdullah_999_sgAdminLoginRoute
  '/skabdullah_999_sg/admin/notifications': typeof Skabdullah_999_sgAdminNotificationsRoute
  '/skabdullah_999_sg/admin/payments': typeof Skabdullah_999_sgAdminPaymentsRoute
  '/skabdullah_999_sg/admin/publishers': typeof Skabdullah_999_sgAdminPublishersRoute
  '/skabdullah_999_sg/admin/security-logs': typeof Skabdullah_999_sgAdminSecurityLogsRoute
  '/skabdullah_999_sg/admin/settings': typeof Skabdullah_999_sgAdminSettingsRoute
  '/skabdullah_999_sg/admin/tasks': typeof Skabdullah_999_sgAdminTasksRoute
  '/skabdullah_999_sg/admin/tutorials': typeof Skabdullah_999_sgAdminTutorialsRoute
  '/skabdullah_999_sg/admin/users': typeof Skabdullah_999_sgAdminUsersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submissions': typeof SubmissionsRoute
  '/app/appeals': typeof AppAppealsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/publish': typeof AppPublishRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/app/wallet': typeof AppWalletRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/skabdullah_999_sg/admin/appeals': typeof Skabdullah_999_sgAdminAppealsRoute
  '/skabdullah_999_sg/admin/dashboard': typeof Skabdullah_999_sgAdminDashboardRoute
  '/skabdullah_999_sg/admin/login': typeof Skabdullah_999_sgAdminLoginRoute
  '/skabdullah_999_sg/admin/notifications': typeof Skabdullah_999_sgAdminNotificationsRoute
  '/skabdullah_999_sg/admin/payments': typeof Skabdullah_999_sgAdminPaymentsRoute
  '/skabdullah_999_sg/admin/publishers': typeof Skabdullah_999_sgAdminPublishersRoute
  '/skabdullah_999_sg/admin/security-logs': typeof Skabdullah_999_sgAdminSecurityLogsRoute
  '/skabdullah_999_sg/admin/settings': typeof Skabdullah_999_sgAdminSettingsRoute
  '/skabdullah_999_sg/admin/tasks': typeof Skabdullah_999_sgAdminTasksRoute
  '/skabdullah_999_sg/admin/tutorials': typeof Skabdullah_999_sgAdminTutorialsRoute
  '/skabdullah_999_sg/admin/users': typeof Skabdullah_999_sgAdminUsersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/submissions'
    | '/app/appeals'
    | '/app/dashboard'
    | '/app/deposit'
    | '/app/notifications'
    | '/app/profile'
    | '/app/publish'
    | '/app/referrals'
    | '/app/settings'
    | '/app/submissions'
    | '/app/tasks'
    | '/app/wallet'
    | '/app/withdraw'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/tasks/$taskId'
    | '/skabdullah_999_sg/admin/appeals'
    | '/skabdullah_999_sg/admin/dashboard'
    | '/skabdullah_999_sg/admin/login'
    | '/skabdullah_999_sg/admin/notifications'
    | '/skabdullah_999_sg/admin/payments'
    | '/skabdullah_999_sg/admin/publishers'
    | '/skabdullah_999_sg/admin/security-logs'
    | '/skabdullah_999_sg/admin/settings'
    | '/skabdullah_999_sg/admin/tasks'
    | '/skabdullah_999_sg/admin/tutorials'
    | '/skabdullah_999_sg/admin/users'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/submissions'
    | '/app/appeals'
    | '/app/dashboard'
    | '/app/deposit'
    | '/app/notifications'
    | '/app/profile'
    | '/app/publish'
    | '/app/referrals'
    | '/app/settings'
    | '/app/submissions'
    | '/app/tasks'
    | '/app/wallet'
    | '/app/withdraw'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/tasks/$taskId'
    | '/skabdullah_999_sg/admin/appeals'
    | '/skabdullah_999_sg/admin/dashboard'
    | '/skabdullah_999_sg/admin/login'
    | '/skabdullah_999_sg/admin/notifications'
    | '/skabdullah_999_sg/admin/payments'
    | '/skabdullah_999_sg/admin/publishers'
    | '/skabdullah_999_sg/admin/security-logs'
    | '/skabdullah_999_sg/admin/settings'
    | '/skabdullah_999_sg/admin/tasks'
    | '/skabdullah_999_sg/admin/tutorials'
    | '/skabdullah_999_sg/admin/users'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/submissions'
    | '/app/appeals'
    | '/app/dashboard'
    | '/app/deposit'
    | '/app/notifications'
    | '/app/profile'
    | '/app/publish'
    | '/app/referrals'
    | '/app/settings'
    | '/app/submissions'
    | '/app/tasks'
    | '/app/wallet'
    | '/app/withdraw'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/tasks/$taskId'
    | '/skabdullah_999_sg/admin/appeals'
    | '/skabdullah_999_sg/admin/dashboard'
    | '/skabdullah_999_sg/admin/login'
    | '/skabdullah_999_sg/admin/notifications'
    | '/skabdullah_999_sg/admin/payments'
    | '/skabdullah_999_sg/admin/publishers'
    | '/skabdullah_999_sg/admin/security-logs'
    | '/skabdullah_999_sg/admin/settings'
    | '/skabdullah_999_sg/admin/tasks'
    | '/skabdullah_999_sg/admin/tutorials'
    | '/skabdullah_999_sg/admin/users'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmissionsRoute: typeof SubmissionsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  Skabdullah_999_sgAdminAppealsRoute: typeof Skabdullah_999_sgAdminAppealsRoute
  Skabdullah_999_sgAdminDashboardRoute: typeof Skabdullah_999_sgAdminDashboardRoute
  Skabdullah_999_sgAdminLoginRoute: typeof Skabdullah_999_sgAdminLoginRoute
  Skabdullah_999_sgAdminNotificationsRoute: typeof Skabdullah_999_sgAdminNotificationsRoute
  Skabdullah_999_sgAdminPaymentsRoute: typeof Skabdullah_999_sgAdminPaymentsRoute
  Skabdullah_999_sgAdminPublishersRoute: typeof Skabdullah_999_sgAdminPublishersRoute
  Skabdullah_999_sgAdminSecurityLogsRoute: typeof Skabdullah_999_sgAdminSecurityLogsRoute
  Skabdullah_999_sgAdminSettingsRoute: typeof Skabdullah_999_sgAdminSettingsRoute
  Skabdullah_999_sgAdminTasksRoute: typeof Skabdullah_999_sgAdminTasksRoute
  Skabdullah_999_sgAdminTutorialsRoute: typeof Skabdullah_999_sgAdminTutorialsRoute
  Skabdullah_999_sgAdminUsersRoute: typeof Skabdullah_999_sgAdminUsersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referrals': {
      id: '/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appeals': {
      id: '/app/appeals'
      path: '/appeals'
      fullPath: '/app/appeals'
      preLoaderRoute: typeof AppAppealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/skabdullah_999_sg/admin/users': {
      id: '/skabdullah_999_sg/admin/users'
      path: '/skabdullah_999_sg/admin/users'
      fullPath: '/skabdullah_999_sg/admin/users'
      preLoaderRoute: typeof Skabdullah_999_sgAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/tutorials': {
      id: '/skabdullah_999_sg/admin/tutorials'
      path: '/skabdullah_999_sg/admin/tutorials'
      fullPath: '/skabdullah_999_sg/admin/tutorials'
      preLoaderRoute: typeof Skabdullah_999_sgAdminTutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/tasks': {
      id: '/skabdullah_999_sg/admin/tasks'
      path: '/skabdullah_999_sg/admin/tasks'
      fullPath: '/skabdullah_999_sg/admin/tasks'
      preLoaderRoute: typeof Skabdullah_999_sgAdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/settings': {
      id: '/skabdullah_999_sg/admin/settings'
      path: '/skabdullah_999_sg/admin/settings'
      fullPath: '/skabdullah_999_sg/admin/settings'
      preLoaderRoute: typeof Skabdullah_999_sgAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/security-logs': {
      id: '/skabdullah_999_sg/admin/security-logs'
      path: '/skabdullah_999_sg/admin/security-logs'
      fullPath: '/skabdullah_999_sg/admin/security-logs'
      preLoaderRoute: typeof Skabdullah_999_sgAdminSecurityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/publishers': {
      id: '/skabdullah_999_sg/admin/publishers'
      path: '/skabdullah_999_sg/admin/publishers'
      fullPath: '/skabdullah_999_sg/admin/publishers'
      preLoaderRoute: typeof Skabdullah_999_sgAdminPublishersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/payments': {
      id: '/skabdullah_999_sg/admin/payments'
      path: '/skabdullah_999_sg/admin/payments'
      fullPath: '/skabdullah_999_sg/admin/payments'
      preLoaderRoute: typeof Skabdullah_999_sgAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/notifications': {
      id: '/skabdullah_999_sg/admin/notifications'
      path: '/skabdullah_999_sg/admin/notifications'
      fullPath: '/skabdullah_999_sg/admin/notifications'
      preLoaderRoute: typeof Skabdullah_999_sgAdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/login': {
      id: '/skabdullah_999_sg/admin/login'
      path: '/skabdullah_999_sg/admin/login'
      fullPath: '/skabdullah_999_sg/admin/login'
      preLoaderRoute: typeof Skabdullah_999_sgAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/dashboard': {
      id: '/skabdullah_999_sg/admin/dashboard'
      path: '/skabdullah_999_sg/admin/dashboard'
      fullPath: '/skabdullah_999_sg/admin/dashboard'
      preLoaderRoute: typeof Skabdullah_999_sgAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skabdullah_999_sg/admin/appeals': {
      id: '/skabdullah_999_sg/admin/appeals'
      path: '/skabdullah_999_sg/admin/appeals'
      fullPath: '/skabdullah_999_sg/admin/appeals'
      preLoaderRoute: typeof Skabdullah_999_sgAdminAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks/$taskId': {
      id: '/app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAppealsRoute: typeof AppAppealsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepositRoute: typeof AppDepositRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPublishRoute: typeof AppPublishRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppWalletRoute: typeof AppWalletRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppealsRoute: AppAppealsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepositRoute: AppDepositRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPublishRoute: AppPublishRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppWalletRoute: AppWalletRoute,
  AppWithdrawRoute: AppWithdrawRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmissionsRoute: SubmissionsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  Skabdullah_999_sgAdminAppealsRoute: Skabdullah_999_sgAdminAppealsRoute,
  Skabdullah_999_sgAdminDashboardRoute: Skabdullah_999_sgAdminDashboardRoute,
  Skabdullah_999_sgAdminLoginRoute: Skabdullah_999_sgAdminLoginRoute,
  Skabdullah_999_sgAdminNotificationsRoute:
    Skabdullah_999_sgAdminNotificationsRoute,
  Skabdullah_999_sgAdminPaymentsRoute: Skabdullah_999_sgAdminPaymentsRoute,
  Skabdullah_999_sgAdminPublishersRoute: Skabdullah_999_sgAdminPublishersRoute,
  Skabdullah_999_sgAdminSecurityLogsRoute:
    Skabdullah_999_sgAdminSecurityLogsRoute,
  Skabdullah_999_sgAdminSettingsRoute: Skabdullah_999_sgAdminSettingsRoute,
  Skabdullah_999_sgAdminTasksRoute: Skabdullah_999_sgAdminTasksRoute,
  Skabdullah_999_sgAdminTutorialsRoute: Skabdullah_999_sgAdminTutorialsRoute,
  Skabdullah_999_sgAdminUsersRoute: Skabdullah_999_sgAdminUsersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
